### ISSUE TITLE
Idea: Provide the file extension when running vale

### ISSUE THREAD

**Issue by johnhamelink** [tpeacock19/flymake-vale#2]
The latest commits on the v2 branch of Vale provide org-mode support! We can take advantage of this by providing the extension, so that it can parse the file appropriately.

Here's an example of vale's new org integration in action:

```
# Using the latest vale from git (v2 branch)
❯ cat to-you-both.org | vale | tail -n1
✖ 37 errors, 72 warnings and 131 suggestions in stdin.
❯ cat to-you-both.org | vale --ext=.org | tail -n1
✖ 33 errors, 71 warnings and 115 suggestions in stdin.
```

This example shows that we can see the improvements in flymake-vale without modification:

```org-mode
#+OPTIONS: foldmarks:nil phone:nil place:nil special-headings:nil subject:nil author:nil date:nil
```

With `flymake-vale-program-args` set to `'("--ext" ".org")`, "special-headings" from the line above is no longer highlighted with the `alex` style enabled in vale.

It'd be really nice, though, if the extension could be detected from the major mode, maybe?

**Comment by tpeacock19** [comment]
Have you made a copyright assignment to the Free Software Foundation? I want to submit this to the Elpa repo and any contributions over 15 lines requires it.

If not, I have a working version written up but I'm happy to keep helping you out on this.

**Comment by johnhamelink** [comment]
@tpeacock19 I actually have, yes! Let me know if you need any form of proof, I can provide that if necessary.

**Comment by tpeacock19** [comment]
oh great. no stress, I don't need proof (at least i dont think? haha)
