### ISSUE TITLE
Git strangeness?

### ISSUE THREAD

**Issue by johnhamelink** [tpeacock19/flymake-vale#5]
Hi again,

Thanks for merging my PR yesterday. I was just promoting it in another github thread, and I noticed that the merged commits don't seem to have made it onto the branch correctly?

![image](https://user-images.githubusercontent.com/101739/177050855-6a94919b-5e6a-4575-aa8e-7140d280e147.png)

![image](https://user-images.githubusercontent.com/101739/177050897-12d5c93a-5117-4eab-baf4-3cdae3dd8e79.png)

Just thought I'd flag it!

**Comment by tpeacock19** [comment]
Ah thanks, there was something wrong with my sync. I'll fix it shortly.

**Comment by tpeacock19** [comment]
okay took a bit more than i thought, but I've merged your commit. It's not linked to the PR, unfortunately, but it's there.

**Comment by johnhamelink** [comment]
No worries at all, thanks!
