### ISSUE TITLE
Unable to get any output on *.adoc files

### ISSUE THREAD

**Issue by 5u623l20** [tpeacock19/flymake-vale#8]
I was trying to use flyamke-vale with this configuration:
```
(straight-use-package
 '(flymake-vale :type git :host github :repo "tpeacock19/flymake-vale"))
(require 'flymake-vale)
(add-hook 'text-mode-hook 'flymake-vale-load)
(add-hook 'latex-mode-hook 'flymake-vale-load)
(add-hook 'org-mode-hook 'flymake-vale-load)
(add-hook 'markdown-mode-hook 'flymake-vale-load)
(add-hook 'message-mode-hook 'flymake-vale-load)

(add-hook 'text-msg-mode-hook (lambda ()
                               (setq flymake-vale-file-ext "adoc")
                               (flymake-vale-load)))
(add-to-list 'flymake-vale-mode-file-exts '(adoc-mode . "adoc"))
(remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)
```

However when run `flymake-mode` there are no outputs in the diagnostic buffer. I can confirm that the vale is running properly.

**Comment by tpeacock19** [comment]
Flymake needs to be loaded with the major mode. These are the only adoc specific lines you should need.

`(add-hook 'adoc-mode-hook #'flymake-load)`
`(add-to-list 'flymake-vale-mode-file-exts '(adoc-mode . "adoc"))`

If you are visiting a file specifically, you do not _need_ to add to the `flymake-vale-mode-file-exts` alist, but it is good to be safe.

What is `text-msg-mode-hook`?

**Comment by 5u623l20** [comment]
Looks like I was missing the `adoc-mode` keyword which I tried to implement through changing the `text-msg-mode-hook`

So now I have updated my config as following:
```
(straight-use-package
 '(flymake-vale :type git :host github :repo "tpeacock19/flymake-vale"))
(require 'flymake-vale)
(add-hook 'adoc-mode-hook #'flymake-load)
(add-hook 'find-file-hook 'flymake-vale-maybe-load)
(add-to-list 'flymake-vale-mode-file-exts '(adoc-mode . "adoc"))
(remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)
```

But still if I run `flymake-mode` nothing happens. There is no log at all in `flymake-show-diagnostic` or `flymake-show-bugger-diagnostic`. And there are actually warning/errors/suggestions in the file that I am trying to edit. Which I have tested with vale itself. I also have tested those in vim+vale and vscode+vale which perfectly shows the errors and suggestions.

In addition to that I am not an Emacs expert. I am just trying to write some documentation for my users so that they can use vale with the choice of their editor/IDE. So I may not be able to give you the obvious informations you need beforehand. But I will be happy to provide any additional information you need to debug this problem.

**Comment by tpeacock19** [comment]
Oh apologies, the function should actually be `flymake-vale-load` for the `adoc-mode-hook`. So there are two ways to activate `flymake-vale`:

# Explicit Activation
```elisp
(add-hook 'adoc-mode-hook #'flymake-vale-load)
```
Call `flymake-vale-load` on the major mode`s hook. This should activate vale regardless of any settings that you have. This would activate vale even when you are not visiting a specific file. For example, if you simply changed the Scratch buffer to `adoc-mode`.

# File Activation
```elisp
(add-hook 'find-file-hook 'flymake-vale-maybe-load)
(add-to-list  'flymake-vale-modes 'adoc-mode)
```
Adding `flymake-vale-maybe-load` to `find-file-hook` causes `flymake-vale` to check, whenever opening a file, if the file's buffer is in the `flymake-vale-modes` list. If so, then it will activate. This will not activate vale in non-file buffers (such as the scratch example above).

In both cases, `flymake-vale` makes `flymake-diagnostic-functions` a buffer local variable, and adds `flymake-vale--checker`. I believe this should remove the need for you to have `(remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)`


Please let me know if this works for you or is more clear. I should update the readme for clarity.

**Comment by 5u623l20** [comment]
No it is still not working. I have updated the configuration as following and my configuration contain nothing but the following just to isolate the problem:
```
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq straight-use-package-by-default t)

(straight-use-package
 '(flymake-vale :type git :host github :repo "tpeacock19/flymake-vale"))
(require 'flymake-vale)
(add-hook 'adoc-mode-hook #'flymake-vale-load)
(add-hook 'find-file-hook 'flymake-vale-maybe-load)
(add-to-list 'flymake-vale-modes 'adoc-mode)
(add-to-list 'flymake-vale-mode-file-exts '(adoc-mode . "adoc"))
;; (remove-hook 'flymake-diagnostic-functions 'flymake-proc-legacy-flymake)
```

And it also does not help with `flymake-proc-legacy-flymake` as I am getting errors like following after removing the remove-hook:
```
Warning [flymake _index.adoc]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
```

In case you want to try out the files I am actually working on you can try any *.adoc files from https://github.com/freebsd/freebsd-doc.

**Comment by tpeacock19** [comment]
Okay, I believe I have narrowed the issue down. Where do you have your vale.ini file located?

**Comment by 5u623l20** [comment]
I have the file in the root of the git repo.
```
git clone https://github.com/freebsd/freebsd-doc.git
cd freebsd-doc
ls .vale.ini
```

The current `.vale.ini` is not suitable for editing with editors as the buffers are created in different locations(vim and vscode creates them in /tmp). So I am using a modified version of the vale.ini which is as following. But I don't want to commit the changes yet without checking emacs. The following config is at least good for vim and vscode. But I am alright to accept further changes for emacs:
```
StylesPath = .vale/styles
MinAlertLevel = suggestion

[asciidoctor]
# enable
experimental = YES

# assign a specific value
attribute-missing = drop

[*.adoc]
BasedOnStyles = FreeBSD

[website/content/{bn-bd,da,de,el,es,fr,hu,id,it,ja,ko,mn,nl,pl,pt-br,ru,tr,zh-cn,zh-tw}/**/*.adoc]
BasedOnStyles = FreeBSD
FreeBSD.BrandTerms = NO
FreeBSD.ConsciousLanguage = NO
FreeBSD.Contractions = NO
FreeBSD.EOLSpacing = NO
FreeBSD.Hang = NO
FreeBSD.Hyphens = NO
FreeBSD.Repitition = NO
FreeBSD.Spacing = NO
FreeBSD.Spelling = NO
FreeBSD.Weasel = NO

[documentation/content/{bn-bd,da,de,el,es,fr,hu,id,it,ja,ko,mn,nl,pl,pt-br,ru,tr,zh-cn,zh-tw}/**/*.adoc]
BasedOnStyles = FreeBSD
FreeBSD.BrandTerms = NO
FreeBSD.ConsciousLanguage = NO
FreeBSD.Contractions = NO
FreeBSD.EOLSpacing = NO
FreeBSD.Hang = NO
FreeBSD.Hyphens = NO
FreeBSD.Repitition = NO
FreeBSD.Spacing = NO
FreeBSD.Spelling = NO
FreeBSD.Weasel = NO
```

**Comment by tpeacock19** [comment]
When I clone this repo I get these errors:

```shell
 ❯ cd ~/src/github/freebsd-doc                                                                                    main 5d ⬡ 2

 ❯ /usr/bin/vale documentation/content/en/languages.adoc                                                            main 2h ⬢
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.

 ❯ cd documentation                                                                                                 main 2h ⬢

 ❯ /usr/bin/vale documentation/content/en/languages.adoc                                                            main 2h ⬢
E201 Invalid value [/home/morpheus/src/github/freebsd-doc/.vale/styles/FreeBSD/Spelling.yml:1:1]:

   1* extends: spelling
   2  message: "'%s' is a typo!"
   3  dicpath: .vale/styles/Dicts

open /home/morpheus/src/github/freebsd-doc/documentation/.vale/styles/Dicts/en_US-default_none_strip_hacker.dic: no such file or directory

Execution stopped with code 1.

```

**Comment by 5u623l20** [comment]
Yes this is actually due to the fact vale's `dicpath` is buggy. `dicpath` is not handled the same way as `StylesPath` so if you run `vale` from any location other than the root folder it generates error. So let's run on an obvious file which has errors:

```
cd ~/src/github/freebsd-doc
/usr/bin/vale documentation/content/en/books/handbook/jails/_index.adoc  
```

Here is an example on how it looks like in vim:

![Screen Shot 2022-11-12 at 6 53 25 PM](https://user-images.githubusercontent.com/6019796/201487977-c1d3dc14-9503-4ae8-b35a-9c418c16774d.png)

**Comment by tpeacock19** [comment]
Right, but in vim, what I imagine you are doing is:
`vim documentation/content/en/books/handbook/jails/_index.adoc`
But if you were to the following, does it still work as expected?
```shell
cd documentation/content/en/books/handbook/jails/
vim _index.adoc
```
The Emacs process will always be in the same folder as the `default-directory`.

If this is a known problem for you with `dicpath`, please create an issue there.

**Comment by 5u623l20** [comment]
If I consider your comment above the fact that the implementation of `Spelling` rule is buggy and remove it from the rules section this should work; unfortunately that is not the case either. I have disabled the `Spelling` rule and still nothing happens in Flymake logs or flymake-show-buffer-diagnostics

**Comment by tpeacock19** [comment]
Does the vim example I sent to you work with the spelling disabled? If you just disable the rule, Vale still needs to parse it which will not work with a broken config file.

**Comment by 5u623l20** [comment]
I have not only disabled it I have also removed it from configuration and now even `vale .` exits with an error: 
```
E100 [.vale.ini] Runtime error

open : no such file or directory

Execution stopped with code 1.
```
So in truth the documentation is also not right:
```
 If it can’t find one, it’ll search up to 6 levels up the file tree.
```
So I have made some changes to the directory structure so that the above works. And now as per your instruction https://github.com/tpeacock19/flymake-vale/issues/8#issuecomment-1312541086 `vim _index.adoc` works but still nothing in emacs.

**Comment by tpeacock19** [comment]
I've pushed a commit that should return any error messages Emacs is seeing in the Flymake Log buffer. I don't know what changes you've made unless they are reflected in the repo.

This is not an issue with flymake-vale, so I'm going to close this. If I can help, let me know.

**Comment by 5u623l20** [comment]
This has been fixed upstream but the problem still persists with Emacs and flymake-vale

**Comment by tpeacock19** [comment]
I just ran the following and it works fine:

`emacs -Q -l ~/. Local/etc/arx-ts/temp.el`

temp.el (init file)
```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq straight-use-package-by-default t)

(straight-use-package
 '(flymake-vale :type git :host github :repo "tpeacock19/flymake-vale"))
(straight-use-package
 '(adoc-mode :type git :flavor melpa :host github :repo "bbatsov/adoc-mode"))
(require 'adoc-mode)
(require 'flymake-vale)
(add-hook 'adoc-mode-hook #'flymake-vale-load)
(add-hook 'find-file-hook 'flymake-vale-maybe-load)
(add-to-list 'flymake-vale-modes 'adoc-mode)
(add-to-list 'flymake-vale-mode-file-exts '(adoc-mode . "adoc"))
```

This works using your repository, as well as any standalone adoc file. Again, this is most likely something to do with the location of your configuration files. Do you have a ~/.vale.ini file? Also, does vale work with any file type, or just an issue with this one?

**Comment by 5u623l20** [comment]
Thanks a lot for the snippet. It works as intended now.

I have just one last query regarding the `find-file-hook`. In the README.md it mentions that run `M-X flymake-mode` otherwise add the hook:
```
(add-hook 'find-file-hook 'flymake-vale-maybe-load)
```
Now as `*.adoc` is in the `flymake-vale-modes` I am expecting that `vale` or in this case `flymake` will run automatically. But it does not and requires me to do `M-X flymake-mode`.

So am I missing something? Or did I fail to understand the documentation?

**Comment by tpeacock19** [comment]
Flymake-vale will not turn on flymake-mode. It simply adds itself as a diagnostic function. Flymake-mode will still need to be turned on. This is how most, if not all, flymake backends behave.
